# Generated by Django 4.1.2 on 2022-10-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Event_ID", models.IntegerField(default=0)),
                ("Person_ID", models.IntegerField(default=0)),
                ("Payment", models.IntegerField(default=0)),
                ("Owed_By", models.CharField(max_length=200)),
            ],
        ),
    ]
