# Generated by Django 4.1.2 on 2022-10-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_image_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Person_ID',
            field=models.CharField(max_length=200),
        ),
    ]
